# Generated by Django 2.1.1 on 2018-09-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pontoturistico_atracoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(related_name='atracao', to='atracoes.Atracao', verbose_name='Atrações'),
        ),
    ]
