# Generated by Django 2.1.1 on 2018-09-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180910_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(related_name='atraco', to='atracoes.Atracao', verbose_name='Atrações'),
        ),
    ]
