# Generated by Django 2.1.1 on 2018-09-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0005_auto_20180910_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(related_name='pontos_turisticos', to='avaliacoes.Avaliacao', verbose_name='Pontos Turísticos'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(related_name='pontos_turisticos', to='atracoes.Atracao', verbose_name='Pontos Turísticos'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(related_name='pontos_turisticos', to='comentarios.Comentario', verbose_name='Pontos Turísticos'),
        ),
    ]
