# Generated by Django 2.1.1 on 2018-09-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0006_auto_20180911_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='enderecos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pontos_turisticos', to='enderecos.Endereco', verbose_name='Endereços'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(related_name='pontos_turisticos', to='atracoes.Atracao', verbose_name='Atrações'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(related_name='pontos_turisticos', to='avaliacoes.Avaliacao', verbose_name='Avaliações'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(related_name='pontos_turisticos', to='comentarios.Comentario', verbose_name='Comentários'),
        ),
    ]
