# Generated by Django 2.1.1 on 2018-09-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180911_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, null=True, related_name='pontos_turisticos', to='avaliacoes.Avaliacao', verbose_name='Avaliações'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(blank=True, null=True, related_name='pontos_turisticos', to='comentarios.Comentario', verbose_name='Comentários'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='enderecos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontos_turisticos', to='enderecos.Endereco', verbose_name='Endereços'),
        ),
    ]
