# Generated by Django 2.1.1 on 2018-09-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=150, verbose_name='Localização')),
                ('referencia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Referência')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=7, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=7, null=True, verbose_name='Longitude')),
            ],
        ),
    ]
